---
url: https://example.com/gorilla/
manifest: example_manifest
catalogs:
  - example_catalog
app_data_path: c:/cpe/gorilla/cache
# auth_user: johnny
# auth_pass: pizza
# service_name: gorilla
# service_interval: 1h
# service_pipe_name: gorilla-service
